config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :comments, only: [:create, :destroy]
    resources :projects, only: [:create, :update, :show, :destroy, :index]
    resources :genres, only: [:index, :show]
    resources :contributions, only: [:create]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many :projects
  has_many :contributions
  has_many :comments

  has_many :backed_projects,
    through: :contributions,
    source: :project

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_out!, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = current_user
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<img class="background" src="http://res.cloudinary.com/daqcetxc6/image/upload/v1445393961/genres/pop_crowd.jpg"/>
<div class="container sign-in">

  <div class="row">
    <h5 class="error-messages"><%= render "layouts/errors" %></h5>
  </div>

  <form action="<%= users_url %>" method="post">
    <%= authenticity_token %>

    <div class="form-group">
      <h1>Sign up</h1>
    </div>

    <div class="form-group">
      <label for="user_username">Username</label>
      <input class="input_text form-control"
             type="text"
             name="user[username]"
             placeholder="username">
    </div>

    <div class="form-group">
      <label for="user_password">Password</label>
      <input class="input_text form-control"
             type="password"
             name="user[password]"
             placeholder="password">
    </div>

    <button type="submit" class="btn btn-default">Sign up</button>

  </form>

  <form action="<%= session_url %>" method="post">
    <input type="hidden" name="user[username]" value="demo">
    <input type="hidden" name="user[password]" value="password">

    <%= authenticity_token %>
    <button type="submit" class="btn btn-default">DEMO - Log in as Justin Vernon</button>
  </form>

</div>