config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"

  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :comments, only: [:create, :destroy]
    resources :projects, only: [:create, :update, :show, :destroy, :index]
    resources :genres, only: [:index, :show]
    resources :contributions, only: [:create]
  end
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
  <title>Pickstarter</title>
  <link href="http://res.cloudinary.com/daqcetxc6/image/upload/c_crop,h_245/v1445540334/genres/logo.png" rel="shortcut icon" type="image/x-icon" />
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="http://widget.cloudinary.com/global/all.js" type="text/javascript" charset="utf-8"></script>
</head>
<body>

<script type="text/javascript" charset="utf-8">
  window.CLOUD_NAME = "<%= ENV['CLOUD_NAME']  %>"
  window.IMAGE_UPLOAD_PRESET = "<%= ENV['IMAGE_UPLOAD_PRESET'] %>"
  window.MUSIC_UPLOAD_PRESET = "<%= ENV['MUSIC_UPLOAD_PRESET'] %>"
</script>

<% if current_user %>
  <script>
    window.CURRENT_USER = JSON.parse('<%= current_user.to_json(only: [:username, :id]).html_safe %>');
  </script>
<% else %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse"
              data-target="#collapse-menu"
              aria-expanded="false">
      </button>
    </div>

    <div class="collapse navbar-collapse" id="collapse-menu">
      <ul class="nav navbar-nav pull-left">
        <button class="logo sign-in"><img class="brand" src="<%= image_path('PICKSTARTER-logo.png') %>"></button>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <li><a href="<%= new_session_url %>">Log in</a></li>
        <li><a href="<%= new_user_url %>">Sign up</a></li>
      </ul>
    </div>

  </div>
  </nav>
<% end %>

<%= yield %>

</body>
</html>